<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-TBA24BB5" name="auditor.AuditorcountStatutory" tests="17" failures="0" timestamp="2022-11-25T18:43:06 IST" time="1352.533" errors="2">
  <testcase name="Login" time="34.949" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="NotCompleted_PieChart" time="148.202" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="ClosedDelayed_PieChart" time="152.556" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="ClosedTimely_PieChart" time="150.027" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="NotApplicable_PieChart" time="81.448" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="Overdue_PieChart" time="54.528" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="dueToday_PieChart" time="49.655" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="pendingForReview_PieChart" time="160.553" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="inProgress_PieChart" time="90.165" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="rejected_PieChart" time="93.541" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="RiskSummaryCriticalStatutory" time="80.495" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="RiskSummaryHighStatutory" time="79.227" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="RiskSummaryMediumStatutory" time="85.274" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="RiskSummaryLowStatutory" time="40.531" classname="auditor.AuditorcountStatutory">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at auditor.AuditorcountStatutory.RiskSummaryLowStatutory(AuditorcountStatutory.java:1134)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- RiskSummaryLowStatutory -->
  <system-out/>
  <testcase name="DepartmentSummaryHumanResourceStatutory" time="1.084" classname="auditor.AuditorcountStatutory">
    <error type="java.lang.NumberFormatException" message="For input string: &quot;&quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at java.lang.Integer.parseInt(Unknown Source)
at auditor.AuditorcountStatutory.DepartmentSummaryHumanResourceStatutory(AuditorcountStatutory.java:1216)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- DepartmentSummaryHumanResourceStatutory -->
  <system-out/>
  <testcase name="DailyUpdates" time="20.166" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
  <testcase name="NewsLetterInternal" time="30.132" classname="auditor.AuditorcountStatutory"/>
  <system-out/>
</testsuite> <!-- auditor.AuditorcountStatutory -->
